# Gemfile
source 'https://rubygems.org'

gem 'firebase_id_token'
gem 'google-id-token'
gem 'json', '~> 2.7'
gem 'pdf-reader', '~> 2.5'
gem 'puma', '~> 6.4'
gem 'sinatra', '~> 3.2'
gem 'ostruct' # Added to silence the startup warning
